#!/usr/bin/env python3
import requests
url= "http://api.open-notify.org/astros.json"
sliceme = requests.get(url).json()

def main():
    print(f"People in Space:  {sliceme['number']}")

    #space_count = int({sliceme['number']}) + 1

    #for every_dict in sliceme['people']:
    #    print(f"{sliceme['people'][every_dict]['name']} is on the ISS")


    for every_dict in sliceme["people"]:
        print(f"{every_dict['name']} is on the ISS")

    
    


    

   #[range.(space_count)]


#   print("TEST ONE")
#    print(f"{sliceme} is on the ISS")
#    print("TEST TWO")
#    print(f"{sliceme['people']} is on the ISS")
#    print("TEST THREE")
#    print(f"{sliceme['people'][0]['name']} is on the ISS")
#    print("TEST FOUR")
#    print(f"{sliceme['people'][0]['name'][0]} is on the ISS") 
     
main()