#!/usr/bin/env python3

# create the string hostname
hostname = "MTG"
hostname = input("What value should we set for hostname?\n>")
# test logic with the `if` statement
# what to do if this statement is found to be true
if hostname.upper() == "MTG":
    print("The hostname was found to be MTG")
    print("The hostname matches expected configuration.")
# Always print to user
print ("End of Script")

