#!/usr/bin/env python3

# ========== IMPORTS ==========
import os
import fileinput

# ========== DICTIONARIES / LISTS ===============
room = {  'porch'     : { 'path'      : [ 'Return to TAXI', 'Enter and go to the RECEPTION' ],
                          'item'      : [],
                          'acts'      : [ 'Inspect INVITATION', 'Oh no! Where did your invitation go?'],
                          'desc'      : 'MONTY HALL PORCH: The driver pulls the taxi up to the curb and you get out. Drizzling rain hastens you out and up the steps to Monty Hall. Renovated in the last three months, the old estate was awash with lights and pouring with music. Costumed up for the bootleg era, you are eager to join your co-workers in the interactive mystery murder theater.'
                        },
          'taxi'      : { 'path'      : [ 'Go to the FOYER', 'foyer' ],
                                        [ 'Take the taxi HOME', 'home' ],
                          'item'      : [],
                          'acts'      : [ 'Search for your INVITATION', 'Found it!'],
                          'desc'      : 'You flag the taxi driver down just before he leaves. "Leaving so soon?" he says.',
                        },



        }
# ========== INITIAL STATE ===============
current_room = room['porch']
current_path = current_room['path'].values()
current_item = current_room['item']
current_acts = current_room['acts']
current_desc = current_room['desc']
current_inv = []
current_input = ""

print("TEST PRINT INITIAL STATE")
print("ROOM", "\n",current_room, "\n")
print("PATH", "\n",current_path, "\n")
print("ITEM", "\n",current_item, "\n")
print("ACTS", "\n",current_acts, "\n")
print("DESC", "\n",current_desc, "\n")
print("INV", "\n",current_inv, "\n")
print(input("PROCEED, PRESS ENTER"))

# ========== STATUS SCREEN ==========
def status():
  os.system("clear")
  print('=========================================================================================')
  print('''
                      ╔╦╗╔═╗╔╗╔╔╦╗╦ ╦  ╦ ╦╔═╗╦  ╦    ╔╦╗╦ ╦╦═╗╔╦╗╔═╗╦═╗
                      ║║║║ ║║║║ ║ ╚╦╝  ╠═╣╠═╣║  ║    ║║║║ ║╠╦╝ ║║║╣ ╠╦╝
                      ╩ ╩╚═╝╝╚╝ ╩  ╩   ╩ ╩╩ ╩╩═╝╩═╝  ╩ ╩╚═╝╩╚══╩╝╚═╝╩╚═
    ''')
  print('=========================================================================================', '\n')
  print()
  print(current_desc, "\n")
  print('=========================================================================================')
  print(f"INVENTORY: {current_inv}")
  print(f"AVAILABLE INTERACTIONS:  {current_acts, current_path, current_item}")
  #print(f"AVAILABLE INTERACTIONS:  {current_acts.keys(), current_path.keys(), current_item.keys.upper()}")
  print('========================================================================================', '\n')

# ========== GAME LOOP ===============
while True:
  status()

  choice = ''
  while choice == '':
    choice = input('Type the name of your next action (shown in caps): ',)
    ch = choice.lower()
    CH = choice.upper()

  if CH in current_room['acts']:                      # EXECUTE ACT / INSPECT OBJECT
    print(current_room['acts'][1])
    continue

  elif ch in current_room['item']:                    # ADD TO INVENTORY, REMOVE FROM ROOM
    for X in current_room['item'][ch]:
      print(f"Picked up: X")
      add.current_inv
    continue

  elif CH in current_inv:                             # REMOVE FROM INVENTORY
    for CH in current_inv:   
      print(f"Dropped: {CH}")
      add.current_room[item]['CH' : '']
    continue

  elif ch in current_room['path']:                    # CHANGE ROOM & UPDATE ALL ROOM VARIABLES
    current_room = ch
    current_path = current_room[ch]
    current_item = current_room['item']
    current_acts = current_room['acts']
    current_desc = current_room['desc']
    continue

  else: continue

