#!/usr/bin/env python3
import os
print(("\n")*2)
print("===== WELCOME TO HANGMAN =====",("\n")*2)


# ESTABLISH THE SECRET WORD
secret = input("Type your secret word: \n>")
secret = secret.lower()
#print(("\n")*40)
os.system("clear")

# BUILD THE LETTER DICTIONARY BASED ON THE SECRET WORD
list_secret = list(secret)
num_letters = len(secret)

# BUILD THE ANSWER DICTIONARY BASED ON GUESSES GIVEN

letter0 = "_"
letter1 = "_"
letter2 = "_"
letter3 = "_"
letter4 = "_"
letter5 = "_"
letter6 = "_"
letter7 = "_"
letter8 = "_"
letter9 = "_"
letter10 = "_"
letter11 = "_"
letter12 = "_"
letter13 = "_"
letter14 = "_"
letter15 = "_"
all_revealed =  "".join([ letter0 , letter1 , letter2 , letter3, letter4, letter5, letter6, letter7, letter8, letter9, letter10, letter11, letter12, letter13, letter14, letter15 ])

# RUN THE GAME
print("===== LET THE GAME BEGIN =====")
print(f"The secret word has {num_letters} letters.\n")
hm_round = 1
win = 0

while hm_round <= 6 and win == 0 : 
    print(("\n")*1)
    print(f"===== ROUND - {hm_round} of 5 =====")
    hm_round = hm_round + 1
    guess= input("Guess a letter: \n>")
    if guess.lower() in list_secret:
        print(f"Your guess '{guess.lower()}' is in the secret word.\n")
        answer = input("What word do you think the secret word is?\n>")
        if answer.lower() == secret:
            print("Your answer is correct.")
            print("===== YOU WIN !!! =====")
            win = 1
        elif hm_round == 6:
            print("Wrong answer. That was your last guess.\n")
            print("===== BETTER LUCK NEXT GAME =====\n")
            break
        else:
            print("Wrong answer. Try again next round.\n")
    else:
        if hm_round <=6 and guess.lower() not in list_secret:
            print(f"Your guess '{guess.lower()}' is not in the secret word.\n")
            answer = input("What word do you think the secret word is?\n>")
            if answer.lower() == secret:
                print("Your answer is correct.")
                print("===== YOU WIN !!! =====")
                win = 1
            elif hm_round == 6:
                print("Wrong answer. That was your last guess.\n")
                print("===== BETTER LUCK NEXT GAME =====")
                break
            else:
                print("Wrong answer. Try again next round.\n")
        else: 
                print("Wrong answer. That was your last guess.\n")
                print("===== BETTER LUCK NEXT GAME =====\n")
                break