#!/usr/bin/env python3
# TEMPLATE
# import os        import filename (no .py req)     #os.system("")
# LIST variable_name = ["key": value, value]       slice by index [0-*]
# DICT variable_name = {                   }       slice by name [""], order irrelevant
# SLICE sliced_var = 
# input(""(\n)*#)
# print(f"Insert text {'variable'} here" )         print(r""" ABSOLUTE TEXT """)
# shutil.copytree("source", "dest")                    relative path > exe in CWD (use fchir or os.chdir(""))
# 
# ========================================================================
def main()                      # import > memorize (EXE: code_file.defined_funciton())
#variable_name = 

#if __name__ == "__main__":
#    while True:
#       main()
#       repeat = input("Run again? Y/N")
        if repeat = "N"
            while = False
main()

